// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RJMCMC_SMC
void RJMCMC_SMC(const NumericVector& T_seg, const IntegerVector& Y_seg, const int& U, const int& K, const int& W, const double& start_point, const double& end_point, const double& t_star, const int& num_logs, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const double& P0, const int& minimum_n, const double& Jss1, const double& Js1s, const int& Smax, const int& n_ite, const int& burn_in, const int& thinning, const int& n_particle, const IntegerVector& particle_index_vec, IntegerVector& V_last_complete, NumericVector& B_last, List& container_B, List& container_V, List& container_Z, List& container_Q, List& container_F, IntegerVector& Svec, NumericVector& weight_vec, const bool& empty_seg);
RcppExport SEXP _RJSMC_RJMCMC_SMC(SEXP T_segSEXP, SEXP Y_segSEXP, SEXP USEXP, SEXP KSEXP, SEXP WSEXP, SEXP start_pointSEXP, SEXP end_pointSEXP, SEXP t_starSEXP, SEXP num_logsSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP Jss1SEXP, SEXP Js1sSEXP, SEXP SmaxSEXP, SEXP n_iteSEXP, SEXP burn_inSEXP, SEXP thinningSEXP, SEXP n_particleSEXP, SEXP particle_index_vecSEXP, SEXP V_last_completeSEXP, SEXP B_lastSEXP, SEXP container_BSEXP, SEXP container_VSEXP, SEXP container_ZSEXP, SEXP container_QSEXP, SEXP container_FSEXP, SEXP SvecSEXP, SEXP weight_vecSEXP, SEXP empty_segSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double& >::type start_point(start_pointSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const double& >::type t_star(t_starSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type Jss1(Jss1SEXP);
    Rcpp::traits::input_parameter< const double& >::type Js1s(Js1sSEXP);
    Rcpp::traits::input_parameter< const int& >::type Smax(SmaxSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_ite(n_iteSEXP);
    Rcpp::traits::input_parameter< const int& >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< const int& >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_particle(n_particleSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type particle_index_vec(particle_index_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type V_last_complete(V_last_completeSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type B_last(B_lastSEXP);
    Rcpp::traits::input_parameter< List& >::type container_B(container_BSEXP);
    Rcpp::traits::input_parameter< List& >::type container_V(container_VSEXP);
    Rcpp::traits::input_parameter< List& >::type container_Z(container_ZSEXP);
    Rcpp::traits::input_parameter< List& >::type container_Q(container_QSEXP);
    Rcpp::traits::input_parameter< List& >::type container_F(container_FSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Svec(SvecSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< const bool& >::type empty_seg(empty_segSEXP);
    RJMCMC_SMC(T_seg, Y_seg, U, K, W, start_point, end_point, t_star, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning, n_particle, particle_index_vec, V_last_complete, B_last, container_B, container_V, container_Z, container_Q, container_F, Svec, weight_vec, empty_seg);
    return R_NilValue;
END_RCPP
}
// SMC_turcotte_cpp
List SMC_turcotte_cpp(const IntegerVector& Yvec, const NumericVector& Tvec, const double& length_UI, const int n_particle, const int U, const int W, const int K, const int& num_logs, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const double& P0, const int& minimum_n, const double& Jss1, const double& Js1s, const int& Smax, const int& n_ite, const int& burn_in, const int& thinning);
RcppExport SEXP _RJSMC_SMC_turcotte_cpp(SEXP YvecSEXP, SEXP TvecSEXP, SEXP length_UISEXP, SEXP n_particleSEXP, SEXP USEXP, SEXP WSEXP, SEXP KSEXP, SEXP num_logsSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP Jss1SEXP, SEXP Js1sSEXP, SEXP SmaxSEXP, SEXP n_iteSEXP, SEXP burn_inSEXP, SEXP thinningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Tvec(TvecSEXP);
    Rcpp::traits::input_parameter< const double& >::type length_UI(length_UISEXP);
    Rcpp::traits::input_parameter< const int >::type n_particle(n_particleSEXP);
    Rcpp::traits::input_parameter< const int >::type U(USEXP);
    Rcpp::traits::input_parameter< const int >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type Jss1(Jss1SEXP);
    Rcpp::traits::input_parameter< const double& >::type Js1s(Js1sSEXP);
    Rcpp::traits::input_parameter< const int& >::type Smax(SmaxSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_ite(n_iteSEXP);
    Rcpp::traits::input_parameter< const int& >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< const int& >::type thinning(thinningSEXP);
    rcpp_result_gen = Rcpp::wrap(SMC_turcotte_cpp(Yvec, Tvec, length_UI, n_particle, U, W, K, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning));
    return rcpp_result_gen;
END_RCPP
}
// SMC_waste_free_cpp
List SMC_waste_free_cpp(const IntegerVector& Yvec, const NumericVector& Tvec, const double& length_UI, const int n_particle, const int U, const int W, const int K, const int& num_logs, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const double& P0, const int& minimum_n, const double& Jss1, const double& Js1s, const int& Smax, const int& n_ite, const int& burn_in, const int& thinning, const int& recycled_particles);
RcppExport SEXP _RJSMC_SMC_waste_free_cpp(SEXP YvecSEXP, SEXP TvecSEXP, SEXP length_UISEXP, SEXP n_particleSEXP, SEXP USEXP, SEXP WSEXP, SEXP KSEXP, SEXP num_logsSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP Jss1SEXP, SEXP Js1sSEXP, SEXP SmaxSEXP, SEXP n_iteSEXP, SEXP burn_inSEXP, SEXP thinningSEXP, SEXP recycled_particlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Tvec(TvecSEXP);
    Rcpp::traits::input_parameter< const double& >::type length_UI(length_UISEXP);
    Rcpp::traits::input_parameter< const int >::type n_particle(n_particleSEXP);
    Rcpp::traits::input_parameter< const int >::type U(USEXP);
    Rcpp::traits::input_parameter< const int >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type Jss1(Jss1SEXP);
    Rcpp::traits::input_parameter< const double& >::type Js1s(Js1sSEXP);
    Rcpp::traits::input_parameter< const int& >::type Smax(SmaxSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_ite(n_iteSEXP);
    Rcpp::traits::input_parameter< const int& >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< const int& >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const int& >::type recycled_particles(recycled_particlesSEXP);
    rcpp_result_gen = Rcpp::wrap(SMC_waste_free_cpp(Yvec, Tvec, length_UI, n_particle, U, W, K, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning, recycled_particles));
    return rcpp_result_gen;
END_RCPP
}
// collapsed_full_conditional_Q
List collapsed_full_conditional_Q(const int& Q, const int& W, const double& count, const double& LB, const double& UB, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_Q, const int& minimum_n, const bool open_segment, double end_point, const bool sample_Q);
RcppExport SEXP _RJSMC_collapsed_full_conditional_Q(SEXP QSEXP, SEXP WSEXP, SEXP countSEXP, SEXP LBSEXP, SEXP UBSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_QSEXP, SEXP minimum_nSEXP, SEXP open_segmentSEXP, SEXP end_pointSEXP, SEXP sample_QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double& >::type count(countSEXP);
    Rcpp::traits::input_parameter< const double& >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< const double& >::type UB(UBSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const bool >::type open_segment(open_segmentSEXP);
    Rcpp::traits::input_parameter< double >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_Q(sample_QSEXP);
    rcpp_result_gen = Rcpp::wrap(collapsed_full_conditional_Q(Q, W, count, LB, UB, alphavec, muvec, probvec_Q, minimum_n, open_segment, end_point, sample_Q));
    return rcpp_result_gen;
END_RCPP
}
// compute_posterior
NumericMatrix compute_posterior(const int num_discr_intervals, const int num_particles, const IntegerMatrix state_container, const int num_states, const NumericVector weight_vec);
RcppExport SEXP _RJSMC_compute_posterior(SEXP num_discr_intervalsSEXP, SEXP num_particlesSEXP, SEXP state_containerSEXP, SEXP num_statesSEXP, SEXP weight_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type num_discr_intervals(num_discr_intervalsSEXP);
    Rcpp::traits::input_parameter< const int >::type num_particles(num_particlesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix >::type state_container(state_containerSEXP);
    Rcpp::traits::input_parameter< const int >::type num_states(num_statesSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type weight_vec(weight_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_posterior(num_discr_intervals, num_particles, state_container, num_states, weight_vec));
    return rcpp_result_gen;
END_RCPP
}
// extract_index
NumericVector extract_index(const NumericVector& x, const double& lower, const double& upper);
RcppExport SEXP _RJSMC_extract_index(SEXP xSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double& >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_index(x, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// full_conditional_F
List full_conditional_F(const int& F, const double& L, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& probvec_F, const bool sample_F);
RcppExport SEXP _RJSMC_full_conditional_F(SEXP FSEXP, SEXP LSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP probvec_FSEXP, SEXP sample_FSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_F(sample_FSEXP);
    rcpp_result_gen = Rcpp::wrap(full_conditional_F(F, L, key0vec, eta0vec, probvec_F, sample_F));
    return rcpp_result_gen;
END_RCPP
}
// full_conditional_V
List full_conditional_V(const int& V, const int& U, const int& num_logs, const NumericVector& T_seg, const IntegerVector& Y_seg, const double& LB, const double& UB, const NumericMatrix& lambdamat, const NumericVector& probvec_V, int V_left, const double& P0, const double& end_point, const bool open_segment, const bool sample_V);
RcppExport SEXP _RJSMC_full_conditional_V(SEXP VSEXP, SEXP USEXP, SEXP num_logsSEXP, SEXP T_segSEXP, SEXP Y_segSEXP, SEXP LBSEXP, SEXP UBSEXP, SEXP lambdamatSEXP, SEXP probvec_VSEXP, SEXP V_leftSEXP, SEXP P0SEXP, SEXP end_pointSEXP, SEXP open_segmentSEXP, SEXP sample_VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const double& >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< const double& >::type UB(UBSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< int >::type V_left(V_leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const bool >::type open_segment(open_segmentSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_V(sample_VSEXP);
    rcpp_result_gen = Rcpp::wrap(full_conditional_V(V, U, num_logs, T_seg, Y_seg, LB, UB, lambdamat, probvec_V, V_left, P0, end_point, open_segment, sample_V));
    return rcpp_result_gen;
END_RCPP
}
// full_conditional_Z
List full_conditional_Z(const int& Z, const int& K, const double& L, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& probvec_Z, const bool& sample_Z);
RcppExport SEXP _RJSMC_full_conditional_Z(SEXP ZSEXP, SEXP KSEXP, SEXP LSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP probvec_ZSEXP, SEXP sample_ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const double& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const bool& >::type sample_Z(sample_ZSEXP);
    rcpp_result_gen = Rcpp::wrap(full_conditional_Z(Z, K, L, keyvec, etavec, probvec_Z, sample_Z));
    return rcpp_result_gen;
END_RCPP
}
// incremental_weight
double incremental_weight(const NumericVector& T_seg, const IntegerVector& Y_seg, const int& V, const int& Z, const int& Q, const int& F, const int& U, const int& K, const int& W, const double& B_last, const double& B1, const int& num_logs, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const int& V_last_complete, const double& P0, const int& minimum_n, const double& t_star, const double& end_point, const bool open_segment);
RcppExport SEXP _RJSMC_incremental_weight(SEXP T_segSEXP, SEXP Y_segSEXP, SEXP VSEXP, SEXP ZSEXP, SEXP QSEXP, SEXP FSEXP, SEXP USEXP, SEXP KSEXP, SEXP WSEXP, SEXP B_lastSEXP, SEXP B1SEXP, SEXP num_logsSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP V_last_completeSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP t_starSEXP, SEXP end_pointSEXP, SEXP open_segmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const int& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const int& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const int& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double& >::type B_last(B_lastSEXP);
    Rcpp::traits::input_parameter< const double& >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const int& >::type V_last_complete(V_last_completeSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type t_star(t_starSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const bool >::type open_segment(open_segmentSEXP);
    rcpp_result_gen = Rcpp::wrap(incremental_weight(T_seg, Y_seg, V, Z, Q, F, U, K, W, B_last, B1, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_last_complete, P0, minimum_n, t_star, end_point, open_segment));
    return rcpp_result_gen;
END_RCPP
}
// initial_breakpoints
NumericVector initial_breakpoints(const NumericVector& T_seg_orig, const double& t_star, const double& start_point, const double& end_point, const int& minimum_n, const double& max_range, const double& min_seg_length);
RcppExport SEXP _RJSMC_initial_breakpoints(SEXP T_seg_origSEXP, SEXP t_starSEXP, SEXP start_pointSEXP, SEXP end_pointSEXP, SEXP minimum_nSEXP, SEXP max_rangeSEXP, SEXP min_seg_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg_orig(T_seg_origSEXP);
    Rcpp::traits::input_parameter< const double& >::type t_star(t_starSEXP);
    Rcpp::traits::input_parameter< const double& >::type start_point(start_pointSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type max_range(max_rangeSEXP);
    Rcpp::traits::input_parameter< const double& >::type min_seg_length(min_seg_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(initial_breakpoints(T_seg_orig, t_star, start_point, end_point, minimum_n, max_range, min_seg_length));
    return rcpp_result_gen;
END_RCPP
}
// initial_state
List initial_state(const NumericVector& T_seg, const IntegerVector& Y_seg, const int& S, const NumericVector& Bvec, const double& end_point, const NumericVector& probvec_V, const NumericVector& probvec_Q, const NumericVector& probvec_Z, const NumericVector& probvec_F, const NumericMatrix& lambdamat, const int& U, const int& W, const int& K, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const double& P0, const int& num_logs, const bool& empty_mix, const int& minimum_n);
RcppExport SEXP _RJSMC_initial_state(SEXP T_segSEXP, SEXP Y_segSEXP, SEXP SSEXP, SEXP BvecSEXP, SEXP end_pointSEXP, SEXP probvec_VSEXP, SEXP probvec_QSEXP, SEXP probvec_ZSEXP, SEXP probvec_FSEXP, SEXP lambdamatSEXP, SEXP USEXP, SEXP WSEXP, SEXP KSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP P0SEXP, SEXP num_logsSEXP, SEXP empty_mixSEXP, SEXP minimum_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Bvec(BvecSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type empty_mix(empty_mixSEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    rcpp_result_gen = Rcpp::wrap(initial_state(T_seg, Y_seg, S, Bvec, end_point, probvec_V, probvec_Q, probvec_Z, probvec_F, lambdamat, U, W, K, alphavec, muvec, keyvec, etavec, key0vec, eta0vec, P0, num_logs, empty_mix, minimum_n));
    return rcpp_result_gen;
END_RCPP
}
// iteration0_RJMCMC
List iteration0_RJMCMC(const NumericVector& T_seg, const IntegerVector& Y_seg, const int& minimum_n, const double& start_point, const double& end_point, const double& t_star, const int& K, const int& W, const int& U, const bool& empty_mix, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericMatrix lambdamat, const double& P0, const int& num_logs, const double& max_range, const int& Smax);
RcppExport SEXP _RJSMC_iteration0_RJMCMC(SEXP T_segSEXP, SEXP Y_segSEXP, SEXP minimum_nSEXP, SEXP start_pointSEXP, SEXP end_pointSEXP, SEXP t_starSEXP, SEXP KSEXP, SEXP WSEXP, SEXP USEXP, SEXP empty_mixSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP lambdamatSEXP, SEXP P0SEXP, SEXP num_logsSEXP, SEXP max_rangeSEXP, SEXP SmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type start_point(start_pointSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const double& >::type t_star(t_starSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const bool& >::type empty_mix(empty_mixSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const double& >::type max_range(max_rangeSEXP);
    Rcpp::traits::input_parameter< const int& >::type Smax(SmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(iteration0_RJMCMC(T_seg, Y_seg, minimum_n, start_point, end_point, t_star, K, W, U, empty_mix, probvec_V, probvec_Z, probvec_Q, probvec_F, alphavec, muvec, keyvec, etavec, key0vec, eta0vec, lambdamat, P0, num_logs, max_range, Smax));
    return rcpp_result_gen;
END_RCPP
}
// prob_approx
double prob_approx(const double& count, const double& split_U, const double& alpha, const double& mu, const int& minimum_n, const double& tau0, const double& tau1, const double& error);
RcppExport SEXP _RJSMC_prob_approx(SEXP countSEXP, SEXP split_USEXP, SEXP alphaSEXP, SEXP muSEXP, SEXP minimum_nSEXP, SEXP tau0SEXP, SEXP tau1SEXP, SEXP errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type count(countSEXP);
    Rcpp::traits::input_parameter< const double& >::type split_U(split_USEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< const double& >::type tau1(tau1SEXP);
    Rcpp::traits::input_parameter< const double& >::type error(errorSEXP);
    rcpp_result_gen = Rcpp::wrap(prob_approx(count, split_U, alpha, mu, minimum_n, tau0, tau1, error));
    return rcpp_result_gen;
END_RCPP
}
// posterior_evaluation
double posterior_evaluation(const NumericVector& T_seg, const IntegerVector& Y_seg, const int& V, const int& Z, const int& Q, const int& F, const int& U, const int& K, const int& W, const double& LB, const double& UB, const int& num_logs, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const int& V_left, const double& P0, const int& minimum_n, const double& count, const double& end_point, const bool open_segment);
RcppExport SEXP _RJSMC_posterior_evaluation(SEXP T_segSEXP, SEXP Y_segSEXP, SEXP VSEXP, SEXP ZSEXP, SEXP QSEXP, SEXP FSEXP, SEXP USEXP, SEXP KSEXP, SEXP WSEXP, SEXP LBSEXP, SEXP UBSEXP, SEXP num_logsSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP V_leftSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP countSEXP, SEXP end_pointSEXP, SEXP open_segmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const int& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const int& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const int& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double& >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< const double& >::type UB(UBSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const int& >::type V_left(V_leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type count(countSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const bool >::type open_segment(open_segmentSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_evaluation(T_seg, Y_seg, V, Z, Q, F, U, K, W, LB, UB, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_left, P0, minimum_n, count, end_point, open_segment));
    return rcpp_result_gen;
END_RCPP
}
// resampling_func
List resampling_func(const NumericVector& weight_vec, const List& container_B, const List& container_V, const List& container_Z, const List& container_Q, const List& container_F, const IntegerVector& Svec, const IntegerVector& V_last_complete, const NumericVector& B_last, int n_particle);
RcppExport SEXP _RJSMC_resampling_func(SEXP weight_vecSEXP, SEXP container_BSEXP, SEXP container_VSEXP, SEXP container_ZSEXP, SEXP container_QSEXP, SEXP container_FSEXP, SEXP SvecSEXP, SEXP V_last_completeSEXP, SEXP B_lastSEXP, SEXP n_particleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< const List& >::type container_B(container_BSEXP);
    Rcpp::traits::input_parameter< const List& >::type container_V(container_VSEXP);
    Rcpp::traits::input_parameter< const List& >::type container_Z(container_ZSEXP);
    Rcpp::traits::input_parameter< const List& >::type container_Q(container_QSEXP);
    Rcpp::traits::input_parameter< const List& >::type container_F(container_FSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Svec(SvecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type V_last_complete(V_last_completeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type B_last(B_lastSEXP);
    Rcpp::traits::input_parameter< int >::type n_particle(n_particleSEXP);
    rcpp_result_gen = Rcpp::wrap(resampling_func(weight_vec, container_B, container_V, container_Z, container_Q, container_F, Svec, V_last_complete, B_last, n_particle));
    return rcpp_result_gen;
END_RCPP
}
// segment_box
List segment_box(const NumericVector& T_seg, const IntegerVector& Y_seg, const int& V, const int& Z, const int& Q, const int& F, const int& U, const int& K, const int& W, const double& LB, const double& UB, const int& num_logs, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const int& V_left, const double& P0, const int& minimum_n, const bool open_segment, const double& end_point, const bool sample_state);
RcppExport SEXP _RJSMC_segment_box(SEXP T_segSEXP, SEXP Y_segSEXP, SEXP VSEXP, SEXP ZSEXP, SEXP QSEXP, SEXP FSEXP, SEXP USEXP, SEXP KSEXP, SEXP WSEXP, SEXP LBSEXP, SEXP UBSEXP, SEXP num_logsSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP V_leftSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP open_segmentSEXP, SEXP end_pointSEXP, SEXP sample_stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Y_seg(Y_segSEXP);
    Rcpp::traits::input_parameter< const int& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const int& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const int& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const double& >::type LB(LBSEXP);
    Rcpp::traits::input_parameter< const double& >::type UB(UBSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const int& >::type V_left(V_leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const bool >::type open_segment(open_segmentSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_state(sample_stateSEXP);
    rcpp_result_gen = Rcpp::wrap(segment_box(T_seg, Y_seg, V, Z, Q, F, U, K, W, LB, UB, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_left, P0, minimum_n, open_segment, end_point, sample_state));
    return rcpp_result_gen;
END_RCPP
}
// shift_function
void shift_function(int& S, const NumericVector& Tvec, const IntegerVector& Yvec, const int& U, const int& K, const int& W, const NumericVector& probvec_V, const NumericVector& probvec_Z, const NumericVector& probvec_Q, const NumericVector& probvec_F, const NumericMatrix& lambdamat, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& alphavec, const NumericVector& muvec, const int& num_logs, NumericVector& Bvec, IntegerVector& Zvec, IntegerVector& Qvec, IntegerVector& Vvec, IntegerVector& Fvec, const double& Jss1, const double& Js1s, const double& P0, const int& minimum_n, const double& start_point, const double& end_point);
RcppExport SEXP _RJSMC_shift_function(SEXP SSEXP, SEXP TvecSEXP, SEXP YvecSEXP, SEXP USEXP, SEXP KSEXP, SEXP WSEXP, SEXP probvec_VSEXP, SEXP probvec_ZSEXP, SEXP probvec_QSEXP, SEXP probvec_FSEXP, SEXP lambdamatSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP alphavecSEXP, SEXP muvecSEXP, SEXP num_logsSEXP, SEXP BvecSEXP, SEXP ZvecSEXP, SEXP QvecSEXP, SEXP VvecSEXP, SEXP FvecSEXP, SEXP Jss1SEXP, SEXP Js1sSEXP, SEXP P0SEXP, SEXP minimum_nSEXP, SEXP start_pointSEXP, SEXP end_pointSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Tvec(TvecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Yvec(YvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_V(probvec_VSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Q(probvec_QSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambdamat(lambdamatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type alphavec(alphavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_logs(num_logsSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Bvec(BvecSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Zvec(ZvecSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Qvec(QvecSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Vvec(VvecSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Fvec(FvecSEXP);
    Rcpp::traits::input_parameter< const double& >::type Jss1(Jss1SEXP);
    Rcpp::traits::input_parameter< const double& >::type Js1s(Js1sSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const int& >::type minimum_n(minimum_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type start_point(start_pointSEXP);
    Rcpp::traits::input_parameter< const double& >::type end_point(end_pointSEXP);
    shift_function(S, Tvec, Yvec, U, K, W, probvec_V, probvec_Z, probvec_Q, probvec_F, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, num_logs, Bvec, Zvec, Qvec, Vvec, Fvec, Jss1, Js1s, P0, minimum_n, start_point, end_point);
    return R_NilValue;
END_RCPP
}
// make_table
NumericVector make_table(IntegerVector X, int K, bool inc_zero);
RcppExport SEXP _RJSMC_make_table(SEXP XSEXP, SEXP KSEXP, SEXP inc_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type inc_zero(inc_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(make_table(X, K, inc_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_findInterval
IntegerVector cpp_findInterval(NumericVector x, NumericVector breaks);
RcppExport SEXP _RJSMC_cpp_findInterval(SEXP xSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_findInterval(x, breaks));
    return rcpp_result_gen;
END_RCPP
}
// saveRObject
void saveRObject(SEXP rObject, std::string filename);
RcppExport SEXP _RJSMC_saveRObject(SEXP rObjectSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rObject(rObjectSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    saveRObject(rObject, filename);
    return R_NilValue;
END_RCPP
}
// augment_vecZQFV
void augment_vecZQFV(IntegerVector& vec, const int left_value, const int right_value, const int IN, const int S);
RcppExport SEXP _RJSMC_augment_vecZQFV(SEXP vecSEXP, SEXP left_valueSEXP, SEXP right_valueSEXP, SEXP INSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const int >::type left_value(left_valueSEXP);
    Rcpp::traits::input_parameter< const int >::type right_value(right_valueSEXP);
    Rcpp::traits::input_parameter< const int >::type IN(INSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    augment_vecZQFV(vec, left_value, right_value, IN, S);
    return R_NilValue;
END_RCPP
}
// augment_vecM
void augment_vecM(NumericVector& vec, const double left_value, const double right_value, const int IN, const int S);
RcppExport SEXP _RJSMC_augment_vecM(SEXP vecSEXP, SEXP left_valueSEXP, SEXP right_valueSEXP, SEXP INSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const double >::type left_value(left_valueSEXP);
    Rcpp::traits::input_parameter< const double >::type right_value(right_valueSEXP);
    Rcpp::traits::input_parameter< const int >::type IN(INSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    augment_vecM(vec, left_value, right_value, IN, S);
    return R_NilValue;
END_RCPP
}
// reduce_vecZQFV
void reduce_vecZQFV(IntegerVector& vec, const int value, const int BR, const int S);
RcppExport SEXP _RJSMC_reduce_vecZQFV(SEXP vecSEXP, SEXP valueSEXP, SEXP BRSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const int >::type value(valueSEXP);
    Rcpp::traits::input_parameter< const int >::type BR(BRSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    reduce_vecZQFV(vec, value, BR, S);
    return R_NilValue;
END_RCPP
}
// reduce_vecM
void reduce_vecM(NumericVector& vec, const double value, const int BR, const int S);
RcppExport SEXP _RJSMC_reduce_vecM(SEXP vecSEXP, SEXP valueSEXP, SEXP BRSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< const int >::type BR(BRSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    reduce_vecM(vec, value, BR, S);
    return R_NilValue;
END_RCPP
}
// augment_Bvec
void augment_Bvec(NumericVector& Bvec, const double T_p, const int IN, const int S);
RcppExport SEXP _RJSMC_augment_Bvec(SEXP BvecSEXP, SEXP T_pSEXP, SEXP INSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type Bvec(BvecSEXP);
    Rcpp::traits::input_parameter< const double >::type T_p(T_pSEXP);
    Rcpp::traits::input_parameter< const int >::type IN(INSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    augment_Bvec(Bvec, T_p, IN, S);
    return R_NilValue;
END_RCPP
}
// reduce_Bvec
void reduce_Bvec(NumericVector& Bvec, const int BR, const int S);
RcppExport SEXP _RJSMC_reduce_Bvec(SEXP BvecSEXP, SEXP BRSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type Bvec(BvecSEXP);
    Rcpp::traits::input_parameter< const int >::type BR(BRSEXP);
    Rcpp::traits::input_parameter< const int >::type S(SSEXP);
    reduce_Bvec(Bvec, BR, S);
    return R_NilValue;
END_RCPP
}
// weigths_correction
double weigths_correction(const NumericVector& T_seg, const List& break_sample_output, const int& M, const int& K, const NumericVector& keyvec, const NumericVector& etavec, const NumericVector& key0vec, const NumericVector& eta0vec, const NumericVector& probvec_Z, const NumericVector& probvec_F, const double& P0);
RcppExport SEXP _RJSMC_weigths_correction(SEXP T_segSEXP, SEXP break_sample_outputSEXP, SEXP MSEXP, SEXP KSEXP, SEXP keyvecSEXP, SEXP etavecSEXP, SEXP key0vecSEXP, SEXP eta0vecSEXP, SEXP probvec_ZSEXP, SEXP probvec_FSEXP, SEXP P0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type T_seg(T_segSEXP);
    Rcpp::traits::input_parameter< const List& >::type break_sample_output(break_sample_outputSEXP);
    Rcpp::traits::input_parameter< const int& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type keyvec(keyvecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type etavec(etavecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type key0vec(key0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eta0vec(eta0vecSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_Z(probvec_ZSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probvec_F(probvec_FSEXP);
    Rcpp::traits::input_parameter< const double& >::type P0(P0SEXP);
    rcpp_result_gen = Rcpp::wrap(weigths_correction(T_seg, break_sample_output, M, K, keyvec, etavec, key0vec, eta0vec, probvec_Z, probvec_F, P0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RJSMC_RJMCMC_SMC", (DL_FUNC) &_RJSMC_RJMCMC_SMC, 40},
    {"_RJSMC_SMC_turcotte_cpp", (DL_FUNC) &_RJSMC_SMC_turcotte_cpp, 27},
    {"_RJSMC_SMC_waste_free_cpp", (DL_FUNC) &_RJSMC_SMC_waste_free_cpp, 28},
    {"_RJSMC_collapsed_full_conditional_Q", (DL_FUNC) &_RJSMC_collapsed_full_conditional_Q, 12},
    {"_RJSMC_compute_posterior", (DL_FUNC) &_RJSMC_compute_posterior, 5},
    {"_RJSMC_extract_index", (DL_FUNC) &_RJSMC_extract_index, 3},
    {"_RJSMC_full_conditional_F", (DL_FUNC) &_RJSMC_full_conditional_F, 6},
    {"_RJSMC_full_conditional_V", (DL_FUNC) &_RJSMC_full_conditional_V, 14},
    {"_RJSMC_full_conditional_Z", (DL_FUNC) &_RJSMC_full_conditional_Z, 7},
    {"_RJSMC_incremental_weight", (DL_FUNC) &_RJSMC_incremental_weight, 29},
    {"_RJSMC_initial_breakpoints", (DL_FUNC) &_RJSMC_initial_breakpoints, 7},
    {"_RJSMC_initial_state", (DL_FUNC) &_RJSMC_initial_state, 23},
    {"_RJSMC_iteration0_RJMCMC", (DL_FUNC) &_RJSMC_iteration0_RJMCMC, 25},
    {"_RJSMC_prob_approx", (DL_FUNC) &_RJSMC_prob_approx, 8},
    {"_RJSMC_posterior_evaluation", (DL_FUNC) &_RJSMC_posterior_evaluation, 29},
    {"_RJSMC_resampling_func", (DL_FUNC) &_RJSMC_resampling_func, 10},
    {"_RJSMC_segment_box", (DL_FUNC) &_RJSMC_segment_box, 29},
    {"_RJSMC_shift_function", (DL_FUNC) &_RJSMC_shift_function, 29},
    {"_RJSMC_make_table", (DL_FUNC) &_RJSMC_make_table, 3},
    {"_RJSMC_cpp_findInterval", (DL_FUNC) &_RJSMC_cpp_findInterval, 2},
    {"_RJSMC_saveRObject", (DL_FUNC) &_RJSMC_saveRObject, 2},
    {"_RJSMC_augment_vecZQFV", (DL_FUNC) &_RJSMC_augment_vecZQFV, 5},
    {"_RJSMC_augment_vecM", (DL_FUNC) &_RJSMC_augment_vecM, 5},
    {"_RJSMC_reduce_vecZQFV", (DL_FUNC) &_RJSMC_reduce_vecZQFV, 4},
    {"_RJSMC_reduce_vecM", (DL_FUNC) &_RJSMC_reduce_vecM, 4},
    {"_RJSMC_augment_Bvec", (DL_FUNC) &_RJSMC_augment_Bvec, 4},
    {"_RJSMC_reduce_Bvec", (DL_FUNC) &_RJSMC_reduce_Bvec, 3},
    {"_RJSMC_weigths_correction", (DL_FUNC) &_RJSMC_weigths_correction, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_RJSMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
