# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title RJMCMC_SMC:  function for generating samples from the important density through RJMCMC updates
#' @param T_seg Vector with time stamps within the update interval
#' @param Y_seg Vector with the messages within the update interval
#' @param U Number of levels of the V state
#' @param W Number of levels of the Q state
#' @param K Number of levels of the Z state
#' @param start_point start point of the update interval
#' @param end_point (const double&) end point of the update interval
#' @param t_star Estimate of the latest changepoint simulated when performing the RJMCMC during the previous iteration of the SMC (precedent update interval)
#' @param num_logs Total number of different messages that can be observed (dictionary)
#' @param lambdamat matrix U*num_logs with probability mass for the messages in each V state
#' @param keyvec Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec Shape parameters ruling the rate of occurrence in different levels of Z state (non-empty segments)
#' @param muvec Mean parameters ruling the rate of occurrence in different levels of Z state
#' @param probvec_V probability mass for the V state
#' @param probvec_Z probability mass for the Z state
#' @param probvec_Q probability mass for the Q state
#' @param probvec_F probability mass for the F state
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param minimum_n minimum number of observations that must be observed in a non-empty segment
#' @param Jss1, (const double&) Probability to propose a jump forward
#' @param Js1s, (const double&) Probability to propose a jump backward
#' @param Smax maximum number of segments allowed inside the update interval
#' @param n_ite (const int&), number of iteration to be performed in the RJMCMC
#' @param burn_in (const int&) Number of iterations used as burn_in period.
#' @param thinning (const int&) 1 every "thinning" iterations will be used
#' @param n_particle number of particles created
#' @param particle_index_vec vector with the index of the particles that will be updated
#' @param V_last_complete Vector with the V state for the last complete segment of each particle
#' @param B_last (NumericVector&) Vector with the last simulated changepoint WITHIN the Update Interval, at the previous SMC iteration
#' @param container_B List for with Bvec generated inside the current Update Interval, for each particle
#' @param container_V List for with Vvec generated inside the current Update Interval, for each particle
#' @param container_Z  List for with Zvec generated inside the current Update Interval, for each particle
#' @param container_Q  List for with Qvec generated inside the current Update Interval, for each particle
#' @param container_F  List for with Fvec generated inside the current Update Interval, for each particle
#' @param Svec vector with number of segment in each particle
#' @param weight_vec vector with the current normalized weight for each particle
#' @param empty_seg (Logical) if true then the importance density for empty segments is used
#' @return The function does not explicitly return any object: However, by reference 9 element are updated:
#' \describe{
#' \item{container_B}{List for with Bvec generated inside the current Update Interval, for each particle}
#' \item{container_V}{List for with Vvec generated inside the current Update Interval, for each particle}
#' \item{container_Z}{List for with Zvec generated inside the current Update Interval, for each particle}
#' \item{container_Q}{List for with Qvec generated inside the current Update Interval, for each particle}
#' \item{container_F}{List for with Fvec generated inside the current Update Interval, for each particle}
#' \item{Svec}{vector with number of segment in each particle}
#' \item{B_last}{Vector with the last simulated changepoint WITHIN the Update Interval, at the previous SMC iteration}
#' \item{V_last_complete}{Vector with the V state for the last complete segment of each particle}
#' \item{weight_vec}{vector with the updated  non normalized weight for each particle}
#' }
#' @export
RJMCMC_SMC <- function(T_seg, Y_seg, U, K, W, start_point, end_point, t_star, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning, n_particle, particle_index_vec, V_last_complete, B_last, container_B, container_V, container_Z, container_Q, container_F, Svec, weight_vec, empty_seg) {
    invisible(.Call(`_RJSMC_RJMCMC_SMC`, T_seg, Y_seg, U, K, W, start_point, end_point, t_star, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning, n_particle, particle_index_vec, V_last_complete, B_last, container_B, container_V, container_Z, container_Q, container_F, Svec, weight_vec, empty_seg))
}

#' SMC Function implementing particle filter for the model in  Gramuglia et al. 2020 using the importance density approximation
#' as in Heard & Turcotte (2017)
#'
#' Given a time series of time-stamp and messages this function run a particle filter with
#' Reversible Jump Markov Chain Montecarlo steps for approximating the posterior distribution for the following variables
#' \itemize{
#'  \item the number of segments
#'  \item the position of the breakpoints defining the segments
#'  \item the state dynamic for each interval which include
#'  \itemize{
#'   \item Z, ruling the length of each non-empty segment
#'   \item Q, ruling the rate of occurrence of the messages in non-empty segments
#'   \item V, ruling the segment composition (in term of messages) in non-empty segments
#'   \item F, ruling the length of empty-segments
#'   }
#'}
#' The algorithm approximate these posterior distributions by splitting the observation
#' time interval in sub-intervals defined by the custom parameter \code{length_UI}
#' @param Yvec IntegerVector  with all the messages
#' @param Tvec NumericVector with all the time-stamps
#' @param length_UI length of the each update interval
#' @param n_particle number of particles created
#' @param U Number of levels of the V state
#' @param W Number of levels of the Q state
#' @param K Number of levels of the Z state
#' @param num_logs Total number of different messages that can be observed (dictionary)
#' @param lambdamat matrix U*num_logs with probability mass for the messages in each V state
#' @param keyvec Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec Shape parameters ruling the rate of occurrence in different levels of Z state (non-empty segments)
#' @param muvec Mean parameters ruling the rate of occurrence in different levels of Z state
#' @param probvec_V probability mass for the V state
#' @param probvec_Z probability mass for the Z state
#' @param probvec_Q probability mass for the Q state
#' @param probvec_F probability mass for the F state
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param minimum_n minimum number of observations that must be observed in a non-empty segment
#' @param Jss1, (const double&) Probability to propose a jump forward
#' @param Js1s, (const double&) Probability to propose a jump backward
#' @param Smax maximum number of segments allowed inside the update interval
#' @param n_ite (const int&), number of iteration to be performed in the RJMCMC
#' @param burn_in (const int&) Number of iterations used as burn_in period.
#' @param thinning (const int&) 1 every "thinning" iterations will be used
#' @export
SMC_turcotte_cpp <- function(Yvec, Tvec, length_UI, n_particle, U, W, K, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning) {
    .Call(`_RJSMC_SMC_turcotte_cpp`, Yvec, Tvec, length_UI, n_particle, U, W, K, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning)
}

#' SMC Function implementing particle filter for the model in  Gramuglia et al. 2020 using the importance density approximation
#' as in Dau & Chopin (2021)
#'
#' Given a time series of time-stamp and messages this function run a particle filter with
#' Reversible Jump Markov Chain Montecarlo steps for approximating the posterior distribution for the following variables
#' \itemize{
#'  \item the number of segments
#'  \item the position of the breakpoints defining the segments
#'  \item the state dynamic for each interval which include
#'  \itemize{
#'   \item Z, ruling the length of each non-empty segment
#'   \item Q, ruling the rate of occurrence of the messages in non-empty segments
#'   \item V, ruling the segment composition (in term of messages) in non-empty segments
#'   \item F, ruling the length of empty-segments
#'   }
#'}
#' The algorithm approximate these posterior distributions by splitting the observation
#' time interval in sub-intervals defined by the custom parameter \code{length_UI}
#' @param Yvec IntegerVector  with all the messages
#' @param Tvec NumericVector with all the time-stamps
#' @param length_UI length of the each update interval
#' @param n_particle number of particles created
#' @param U Number of levels of the V state
#' @param W Number of levels of the Q state
#' @param K Number of levels of the Z state
#' @param num_logs Total number of different messages that can be observed (dictionary)
#' @param lambdamat matrix U*num_logs with probability mass for the messages in each V state
#' @param keyvec Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec Shape parameters ruling the rate of occurrence in different levels of Z state (non-empty segments)
#' @param muvec Mean parameters ruling the rate of occurrence in different levels of Z state
#' @param probvec_V probability mass for the V state
#' @param probvec_Z probability mass for the Z state
#' @param probvec_Q probability mass for the Q state
#' @param probvec_F probability mass for the F state
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param minimum_n minimum number of observations that must be observed in a non-empty segment
#' @param Jss1, (const double&) Probability to propose a jump forward
#' @param Js1s, (const double&) Probability to propose a jump backward
#' @param Smax maximum number of segments allowed inside the update interval
#' @param n_ite (const int&), number of iteration to be performed in the RJMCMC
#' @param burn_in (const int&) Number of iterations used as burn_in period.
#' @param thinning (const int&) 1 every "thinning" iterations will be used
#' @param recycled_particles (const int&) number of particles that will be recycled according to the waste free method
#' @export
SMC_waste_free_cpp <- function(Yvec, Tvec, length_UI, n_particle, U, W, K, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning, recycled_particles) {
    .Call(`_RJSMC_SMC_waste_free_cpp`, Yvec, Tvec, length_UI, n_particle, U, W, K, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, P0, minimum_n, Jss1, Js1s, Smax, n_ite, burn_in, thinning, recycled_particles)
}

#' @title backward_function
#' This function takes in the current state of the MCMC and employ a forward step where a split of an interval is proposed
#' all the input parameters described below refers to their  ost recent values.
#' @param S (int). The total number of interarrivals (intervals).
#' @param Tvec (const NumericVector). Vector of the observed time stamps in the update interval
#' @param Yvec (const IntegerVector). Vector of the observed messages in the update interval
#' @param U (const int&) Number of levels for the V state
#' @param K (const int&) Number of levels of the Z state
#' @param W (const int&) Number of levels for the Q state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state.
#' @param num_logs (const int). Total numer of different logs (levels of the factor )
#' @param Bvec (NumericVector). Current vector of changepoints
#' @param Zvec (IntegerVector). Current vector with Z state of each  segment
#' @param Qvec (IntegerVector). Current vector with Q state of each  segment
#' @param Vvec (IntegerVector). Current vector with V state of each  segment
#' @param Fvec (IntegerVector). Current vector with F state of each  segment
#' @param Jss1 (const double). Probability to propose a forward move
#' @param Js1s (const double). Probability to propose a backward move
#' @param P0 (const double&) probability of observing a non-empty segment after a empty one
#' @param minimum_n (const int&) minimum number of observations in a non-empty segment
#' @param start_point (double, default is 0.0) start of the update interval
#' @param end_point (double, default is 0.0) end of the update interval; to be used for partially observed segments
#' @name backward_function
NULL

#' @title collapsed_full_conditional_Q
#' Function for sampling the Q  state for a  new non-empty segment from its  collpsed full conditional and/or evaluate it at the sampled point
#' It is "collapsed" because the likelihood part is not Gamma(M,alpha_q,alpha_q/mu_q) but
#' shifted Neg-Bin (N;alpha_q,L/(alpha_q/mu_q + L)). M is integrated out because not needed
#' @param Q (const int&) Value of the current Q if present; if not set it 0.
#' @param W (const int&) Number of levels for the Q state
#' @param count (const double&) number of observations within the selected segment
#' @param LB (const double&) lower bound of the selected segment
#' @param UB (const double&) upper bound of the selected segment
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param minimum_n minimum number of observations that must be observed in a non-empty segment
#' @param open_segment (const bool) if false (by default) the segment is considered totally observed. If true the semgent is considered partially observed; this affects the likelihood computation
#' @param end_point (double, default is 0.0) to be used for partially observed segments; declares the point where the stops to be observed
#' @param sample_Q ( const bool=false) if true a new Q is sampled and the full conditional is evaluated at the new value. If false (by default) the full condititional is evaluated at the input Q
#' @return A list containting 2 elements:
#' \describe{
#' \item{Q_new}{int, the sample Q state for the selected segment}
#' \item{eval_densQ}{double, value of the log full conditional for either the new sampled Q or the current Q inputed ( depending on sample_Q)}
#' }
#' @export
collapsed_full_conditional_Q <- function(Q, W, count, LB, UB, alphavec, muvec, probvec_Q, minimum_n, open_segment = FALSE, end_point = 0.0, sample_Q = FALSE) {
    .Call(`_RJSMC_collapsed_full_conditional_Q`, Q, W, count, LB, UB, alphavec, muvec, probvec_Q, minimum_n, open_segment, end_point, sample_Q)
}

#'
#' Function for updating the posterior distribution of state variables
#' @param num_discr_intervals (int) number of discretization intervals
#' @param num_particles (int) number of particles
#' @param state_container (IntegerMatrix) with inferred state values for each discretization interval, for each particle
#' @param num_states (int) number of states
#' @param weight_vec (NumericVector) weights assigned to each particle
#' @export
compute_posterior <- function(num_discr_intervals, num_particles, state_container, num_states, weight_vec) {
    .Call(`_RJSMC_compute_posterior`, num_discr_intervals, num_particles, state_container, num_states, weight_vec)
}

#'
#' Function for computing the posterior distribution of breakpoint locations
#' @param num_discr_intervals (int) number of discretization intervals
#' @param num_particles (int) number of particles
#' @param state_container_B (NumericMatrix) matrix indicating breakpoint presence: 1 if particle j has a breakpoint in interval i, 0 otherwise
#' @param weight_vec (NumericVector) weights assigned to each particle (should sum to 1)
#' @return NumericVector posterior probability that a breakpoint occurs in each discretization interval
#' @export
compute_posterior_breakpoint <- function(num_discr_intervals, num_particles, state_container_B, weight_vec) {
    .Call(`_RJSMC_compute_posterior_breakpoint`, num_discr_intervals, num_particles, state_container_B, weight_vec)
}

#' @title extract_index
#' Function for extracting the first and last index elements of an ordered vector
#' sastisfying a constraint specified by a lower and upper bound
#' @param  x (const NumericVector&) the original vector
#' @param  lower (const double), the lower bound (included in the subsetting)
#' @param  upper (const double), the lower bound
#' @return 3-element vector with:
#' \describe{
#' \item{element \code{[0]}}{length of the subsetted vector}
#' \item{element \code{[1]}}{index of the first element of the subsetted vector }
#' \item{element \code{[2]}}{index of the last element of the subsetted vector. If the last index is "-1" then no elements sastisfy the constraint}
#' }
extract_index <- function(x, lower, upper) {
    .Call(`_RJSMC_extract_index`, x, lower, upper)
}

#' @title forward_function
#' This function takes in the current state of the MCMC and employ a forward step where a split of an interval is proposed
#' all the input parameters described below refers to their  most recent values.
#' @param S (int). The total number of interarrivals (intervals).
#' @param Tvec (const NumericVector). Vector of the observed time stamps in the update interval
#' @param Yvec (const IntegerVector). Vector of the observed messages in the update interval
#' @param U (const int&) Number of levels for the V state
#' @param K (const int&) Number of levels of the Z state
#' @param W (const int&) Number of levels for the Q state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state.
#' @param num_logs (const int). Total numer of different logs (levels of the factor )
#' @param Bvec (NumericVector). Current vector of changepoints
#' @param Zvec (IntegerVector). Current vector with Z state of each  segment
#' @param Qvec (IntegerVector). Current vector with Q state of each  segment
#' @param Vvec (IntegerVector). Current vector with V state of each  segment
#' @param Fvec (IntegerVector). Current vector with F state of each  segment
#' @param Jss1 (const double). Probability to propose a forward move
#' @param Js1s (const double). Probability to propose a backward move
#' @param P0 (const double&) probability of observing a non-empty segment after a empty one
#' @param minimum_n (const int&) minimum number of observations in a non-empty segment
#' @param start_point (double, default is 0.0) start of the update interval
#' @param end_point (double, default is 0.0) end of the update interval; to be used for partially observed segments
#' @name forward_function
NULL

#' @title full_conditional_F
#' Function for sampling the F state for a  new empty segment from its full conditional and/or evaluate it at the sampled point
#' @param F (const int&) Value of the current F if present; if not set it 0.
#' @param L (const double&) Length of the selected segment
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segment for the different levels of the F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segment for the different levels of the F state
#' @param probvec_F (const NumericVector&) Probability mass for the F state distribution
#' @param sample_F ( const bool=false) if true a new F is sampled and the full conditional is evaluated at the new value. If false (by default) the full condititional is evaluated at the input F
#' @return A list containting 2 elements:
#' \describe{
#' \item{F_new}{int, the sample F state for the selected segment}
#' \item{eval_densF}{double, value of the  log full conditional for either the new F sampled of the current F inputed ( depending on sample_F)}
#' }
#' @name full_conditional_F
full_conditional_F <- function(F, L, key0vec, eta0vec, probvec_F, sample_F = FALSE) {
    .Call(`_RJSMC_full_conditional_F`, F, L, key0vec, eta0vec, probvec_F, sample_F)
}

#' @title full_conditional_V
#' Function for sampling the V  state for a  new non-empty segment from its full conditional and/or evaluate it at the sampled point
#' @param V (const int&) Value of the current V if present; if not set it 0.
#' @param U (const int&) Number of levels for the V state
#' @param num_logs (const int&) Total number of unique messages that can be observed
#' @param T_seg (const NumericVector&) Vector with time stamps within the update interval
#' @param Y_seg (const IntegerVector&) Vector with the messages within the update interval
#' @param LB (const double&) lower bound of the selected segment
#' @param UB (const double&) upper bound of the selected segment
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param V_left  V value for the previous segment
#' @param open_segment (const bool, default is false) if false  the segment is considered totally observed. If true the semgent is considered partially observed; this affects the likelihood computation
#' @param end_point (double, default is 0.0) to be used for partially observed segments; declares the point where the stops to be observed
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param sample_V ( const bool=false) if true a new V is sampled and the full conditional is evaluated at the new value. If false (by default) the full condititional is evaluated at the input V
#' @return A list containting 2 elements:
#' \describe{
#' \item{V_new}{int, the sample Vstate for the selected segment or the one inputed}
#' \item{eval_densV}{double, value of the log full conditional for either the new sampled V or the current Q inputed ( depending on sample_V)}
#' }
#' @name full_conditional_V
full_conditional_V <- function(V, U, num_logs, T_seg, Y_seg, LB, UB, lambdamat, probvec_V, V_left, P0, end_point = 0.0, open_segment = FALSE, sample_V = FALSE) {
    .Call(`_RJSMC_full_conditional_V`, V, U, num_logs, T_seg, Y_seg, LB, UB, lambdamat, probvec_V, V_left, P0, end_point, open_segment, sample_V)
}

#' @title full_conditional_Z
#' Function for sampling the Z state for a  new non-empty segment from its full conditional and/or evaluate it at the sampled point
#' @param Z (const int&) Value of the current Z if present; if not set it 0.
#' @param K (const int&) Number of levels for the Z state
#' @param L (const double&) Length of the selected segment
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of segment for the different levels of the Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of segment for the different levels of the Z state
#' @param probvec_Z (const NumericVector&) Probability mass for the Z state distribution
#' @param sample_Z ( const bool=false) if true a new Z is sampled and the full conditional is evaluated at the new value. If false (by default) the full condititional is evaluated at the input Z
#' @return A list containting 2 elements:
#' \describe{
#' \item{Z_new}{int, the sample Z state for the selected segment}
#' \item{eval_densZ}{double, value of the  log full conditional for either the new Z sampled of the current Z inputed ( depending on sample_Z)}
#' }
#' @name full_conditional_Z
full_conditional_Z <- function(Z, K, L, keyvec, etavec, probvec_Z, sample_Z = FALSE) {
    .Call(`_RJSMC_full_conditional_Z`, Z, K, L, keyvec, etavec, probvec_Z, sample_Z)
}

#' @title Incremental_weight
#' Function for computing the log incremental weight for a particle
#' @param T_seg Vector with time stamps within the update interval
#' @param Y_seg Vector with the messages within the update interval
#' @param V (const int&) Value of the current V if present; if not set it 0.
#' @param Z (const int&) Value of the current Z if present; if not set it 0.
#' @param Q (const int&) Value of the current Q if present; if not set it 0.
#' @param F (const int&) Value of the current F if present; if not set it 0.
#' @param U (const int&) Number of levels for the V state
#' @param K (const int&) Number of levels of the Z state
#' @param W (const int&) Number of levels for the Q state
#' @param B_last Last simulated changepoint WITHIN the Update Interval, at the previous SMC iteration
#' @param B1 (const double&) first generate changepoint, at the current SMC iteration
#' @param num_logs (const int&) Total number of unique messages that can be observed
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param V_last_complete (const int&) V value for the last "closed" segment generated during the previous SMC iteration
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param minimum_n (const int&) minimum number of observations that must be observed in a non-empty segment
#' @param t_star, (double) estimate of the last simulated breakpoint
#' @param end_point (double, default is 0.0) to be used for partially observed segments; declares the point where the segment stops to be observed
#' @param open_segment (const bool, default is false) if false  the segment is considered totally observed. If true the segment is considered partially observed; this affects the likelihood computation
#' @export
incremental_weight <- function(T_seg, Y_seg, V, Z, Q, F, U, K, W, B_last, B1, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_last_complete, P0, minimum_n, t_star, end_point = 0.0, open_segment = FALSE) {
    .Call(`_RJSMC_incremental_weight`, T_seg, Y_seg, V, Z, Q, F, U, K, W, B_last, B1, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_last_complete, P0, minimum_n, t_star, end_point, open_segment)
}

#' @title initial_breakpoints
#' Function to initialize the changepoint vector during the first iteration of the RJMCMC
#' @param T_seg_orig Vector with time stamps within the update interval
#' @param t_star Estimate of the latest changepoint simulated when performing the RJMCMC during the previous iteration of the SMC (precedent update interval)
#' @param start_point Left bound of the current update interval
#' @param end_point Right bound of the current update interval
#' @param minimum_n minimum number of observation allowed in a non-empty segment
#' @param max_range (const double&) time interval in which the last changepoint is allowed to be place after the end point (end_point;end_point+1)
#' @param min_seg_length (const double) minimum length allowed for a segment to be valid
#' @return NumericVector with the generated changepoints. Starting with t_star, ending with B_k > UB
#' @export
initial_breakpoints <- function(T_seg_orig, t_star, start_point, end_point, minimum_n, max_range, min_seg_length) {
    .Call(`_RJSMC_initial_breakpoints`, T_seg_orig, t_star, start_point, end_point, minimum_n, max_range, min_seg_length)
}

#' @title initial_state
#' Function for generating the initial state values in each segment
#' @param T_seg Vector with time stamps within the update interval
#' @param Y_seg Vector with the messages within the update interval
#' @param S Number of segments within the update interval
#' @param Bvec Position of the Changepoints simulated within the update interval
#' @param end_point (const double&) end point of the update interval
#' @param probvec_V probability mass for the V state
#' @param probvec_Q probability mass for the Q state
#' @param probvec_Z probability mass for the Z state
#' @param probvec_F probability mass for the F state
#' @param lambdamat matrix U*num_logs with probability mass for the messages in each V state
#' @param U Number of levels of the V state
#' @param W Number of levels of the Q state
#' @param K Number of levels of the Z state
#' @param alphavec Shape parameters ruling the rate of occurrence in different levels of Z state (non-empty segments)
#' @param muvec Mean parameters ruling the rate of occurrence in different levels of Z state
#' @param keyvec Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec Mean parameters ruling the length of empty segments in different levels of F state
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param num_logs Total number of different messages that can be observed (dictionary)
#' @param empty_mix Logical. Equal "true" if the empty segments are a mixture of the states
#' @param minimum_n minimum number of observations that must be observed in a non-empty segment
#' @return A list containting 6 elements:
#' \describe{
#' \item{Vvec}{IntegerVector,  initial V state for each segment }
#' \item{Zvec}{IntegerVector,  initial Z state for each segment }
#' \item{Qvec}{IntegerVector,  initial Q state for each segment }
#' \item{Fvec}{IntegerVector,  initial F state for each segment }
#' \item{Mvec}{NumericVector,  initial M (rate) for each segment }
#' \item{Nvec}{NumericVector, count of observations in each segment }
#' }
#' @export
initial_state <- function(T_seg, Y_seg, S, Bvec, end_point, probvec_V, probvec_Q, probvec_Z, probvec_F, lambdamat, U, W, K, alphavec, muvec, keyvec, etavec, key0vec, eta0vec, P0, num_logs, empty_mix, minimum_n) {
    .Call(`_RJSMC_initial_state`, T_seg, Y_seg, S, Bvec, end_point, probvec_V, probvec_Q, probvec_Z, probvec_F, lambdamat, U, W, K, alphavec, muvec, keyvec, etavec, key0vec, eta0vec, P0, num_logs, empty_mix, minimum_n)
}

#' @title Function to initialize the MCMC in RJMCMC_SMC
#' Function generating the first iteration of the MCMC
#' @param T_seg Vector with time stamps within the update interval
#' @param Y_seg Vector with the messages within the update interval
#' @param minimum_n (int) minimum allowed number of observations in a active segments
#' @param start_point, (double)   the start point of the update interval
#' @param end_point, (double)   the end point of the update interval
#' @param t_star, (double) estimate of the last simulated breakpoint
#' @param K (int) number of Z states
#' @param W (int) Number of levels for the Q state
#' @param U (int) Number of V states
#' @param empty_mix (bool) If True (default) 2 kind of empty segments are assumed
#' @param probvec_V probability mass for the V state
#' @param probvec_Z probability mass for the Z state
#' @param probvec_Q probability mass for the Q state
#' @param probvec_F probability mass for the F state
#' @param alphavec Shape parameters ruling the rate of occurrence in different levels of Z state (non-empty segments)
#' @param muvec Mean parameters ruling the rate of occurrence in different levels of Z state
#' @param keyvec Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec Mean parameters ruling the length of empty segments in different levels of F state
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param lambdamat (const NumericMatrix&) each row v is the full prob vector for the messages of state V=v
#' @param num_logs Total number of different messages that can be observed (dictionary)
#' @param max_range (const double&) time interval in which the last changepoint is allowed to be place after the end point (end_point;end_point+1)
#' @param Smax maximum number of segments allowed inside the update interval
#' @return A list containting 8 elements:
#' \describe{
#' \item{S}{int, number of segments generarted}
#' \item{Bvec}{NumericVector, hosts the changepoints generated (inlcuding t_star, tau_k (last breakpoint after end_point)) }
#' \item{Vvec}{IntegerVector,  initial V state for each segment }
#' \item{Zvec}{IntegerVector,  initial Z state for each segment }
#' \item{Qvec}{IntegerVector,  initial Q state for each segment }
#' \item{Fvec}{IntegerVector,  initial F state for each segment }
#' \item{Mvec}{NumericVector,  initial M (rate) for each segment }
#' \item{Nvec}{NumericVector, count of observations in each segment }
#' }
#' @export
iteration0_RJMCMC <- function(T_seg, Y_seg, minimum_n, start_point, end_point, t_star, K, W, U, empty_mix, probvec_V, probvec_Z, probvec_Q, probvec_F, alphavec, muvec, keyvec, etavec, key0vec, eta0vec, lambdamat, P0, num_logs, max_range, Smax) {
    .Call(`_RJSMC_iteration0_RJMCMC`, T_seg, Y_seg, minimum_n, start_point, end_point, t_star, K, W, U, empty_mix, probvec_V, probvec_Z, probvec_Q, probvec_F, alphavec, muvec, keyvec, etavec, key0vec, eta0vec, lambdamat, P0, num_logs, max_range, Smax)
}

#' @title Function for approximating the log probability of observing "n" obs in semi-segment [tau0,split_U) given
#' the total length [tau0,tau1)
#' @param count (double& int) number of observations within the selected segment
#' @param split_U (const& double) point where the update interval ends
#' @param alpha (const& double) shape parameter for the rate
#' @param mu (const& double) mean parameter for the rate
#' @param minimum_n (const& int) minimum number of observations allowed in a non-empty segment
#' @param tau0 (const& double) left bound of the segment
#' @param tau1 (const& double) right bound of the segment
#' @param error (const& double) approximation error
#' @return the value of the log density
prob_approx <- function(count, split_U, alpha, mu, minimum_n, tau0, tau1, error) {
    .Call(`_RJSMC_prob_approx`, count, split_U, alpha, mu, minimum_n, tau0, tau1, error)
}

#' @title  posterior_evaluation
#' Function for evaluating the joint posterior distribution of all the quantities related to a closed or open  segment (T,Y,V,Z,Q,F)
#'
#' @param T_seg Vector with time stamps within the update interval
#' @param Y_seg Vector with the messages within the update interval
#' @param V (const int&) Value of the current V if present; if not set it 0.
#' @param Z (const int&) Value of the current Z if present; if not set it 0.
#' @param Q (const int&) Value of the current Q if present; if not set it 0.
#' @param F (const int&) Value of the current F if present; if not set it 0.
#' @param U (const int&) Number of levels for the V state
#' @param K (const int&) Number of levels of the Z state
#' @param W (const int&) Number of levels for the Q state
#' @param LB (const double&) lower bound of the selected segment
#' @param UB (const double&) upper bound of the selected segment
#' @param num_logs (const int&) Total number of unique messages that can be observed
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param V_left (const int&) V value for the previous segment
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param minimum_n (const int&) minimum number of observations that must be observed in a non-empty segment
#' @param count (const double&) number of observarions inside the selected segment
#' @param open_segment (const bool, default is false) if false  the segment is considered totally observed. If true the semgent is considered partially observed; this affects the likelihood computation
#' @param end_point (double, default is 0.0) to be used for partially observed segments; declares the point where the stops to be observed
#' @return  List with 6 elements
#' \describe{
#' \item{ldens_tmsp}{double,likelihood of the time-stamps positions within the selected segment }
#' \item{ldens_count}{double, likelihood for the count of observations withing the selected segment }
#' \item{ldens_event}{double,  likelihood for the messages within the selected segment}
#' \item{ldens_empty}{double, prior probability to observe state F in the selected segment}
#' \item{ldens_L}{double, prior for  the length of the selected segment}
#' \item{ldens_dynamics}{double, prior probability to observe state V, Z and Q in the selected segment}
#' }
#' @export
posterior_evaluation <- function(T_seg, Y_seg, V, Z, Q, F, U, K, W, LB, UB, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_left, P0, minimum_n, count, end_point = 0.0, open_segment = FALSE) {
    .Call(`_RJSMC_posterior_evaluation`, T_seg, Y_seg, V, Z, Q, F, U, K, W, LB, UB, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_left, P0, minimum_n, count, end_point, open_segment)
}

#' @title systematic_resampling:  function for performing systematic resampling
#'
#' @param weight_vec vector with the current normalized weight for each particle
#' @param container_B List for with Bvec generated inside the current Update Interval, for each particle
#' @param container_V List for with Vvec generated inside the current Update Interval, for each particle
#' @param container_Z  List for with Zvec generated inside the current Update Interval, for each particle
#' @param container_Q  List for with Qvec generated inside the current Update Interval, for each particle
#' @param container_F  List for with Fvec generated inside the current Update Interval, for each particle
#' @param Svec vector with number of segment in each particle
#' @param V_last_complete Vector with the V state for the last complete segment of each particle
#' @param B_last (NumericVector&) Vector with the last simulated changepoint WITHIN the Update Interval, at the previous SMC iteration
#' @param n_particle number of particles created
#' @return The function does not explicitly return any object: However, by reference 9 element are updated:
#' @export
resampling_func <- function(weight_vec, container_B, container_V, container_Z, container_Q, container_F, Svec, V_last_complete, B_last, n_particle) {
    .Call(`_RJSMC_resampling_func`, weight_vec, container_B, container_V, container_Z, container_Q, container_F, Svec, V_last_complete, B_last, n_particle)
}

#' @title center_segment_box
#' Function for computing all the necessary quantities needed for updating/evaluating a CLOSED segment or an OPEN segment with at least 1 obs inside.
#' This function will either sample new states V,Z,Q,F or use the current ones to evaluate the joint proposal and
#'  and the joint posterior distribution for these values
#' @param T_seg Vector with time stamps within the update interval
#' @param Y_seg Vector with the messages within the update interval
#' @param V (const int&) Value of the current V if present; if not set it 0.
#' @param Z (const int&) Value of the current Z if present; if not set it 0.
#' @param Q (const int&) Value of the current Q if present; if not set it 0.
#' @param F (const int&) Value of the current F if present; if not set it 0.
#' @param U (const int&) Number of levels for the V state
#' @param K (const int&) Number of levels of the Z state
#' @param W (const int&) Number of levels for the Q state
#' @param LB (const double&) lower bound of the selected segment
#' @param UB (const double&) upper bound of the selected segment
#' @param num_logs (const int&) Total number of unique messages that can be observed
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param V_left (const int&) V value for the previous segment
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @param minimum_n (const int&) minimum number of observations that must be observed in a non-empty segment
#' @param open_segment (const bool, default is false) if false  the segment is considered totally observed. If true the semgent is considered partially observed; this affects the likelihood computation
#' @param end_point (double, default is 0.0) to be used for partially observed segments; declares the point where the stops to be observed
#' @param sample_state (const bool=false) if true new V,Z,Q,F are sampled and the full conditional are evaluated at the new values. If false (by default) the full condititionals are evaluated at the input provided
#' @return List with 6 elements
#' \describe{
#' \item{V}{int,Value of the current or new V}
#' \item{Z}{int,Value of the current or new Z}
#' \item{Q}{int,Value of the current or new Q}
#' \item{F}{int,Value of the current or new F}
#' \item{sum_proposals}{double,sum of the log proposal for the current or new values of V, Z, Q and F }
#' \item{out_posterior_evaluation}{double, joint log posterior distribuion for the quantities related to the selected segment }
#' }
#' @export
segment_box <- function(T_seg, Y_seg, V, Z, Q, F, U, K, W, LB, UB, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_left, P0, minimum_n, open_segment = FALSE, end_point = 0.0, sample_state = FALSE) {
    .Call(`_RJSMC_segment_box`, T_seg, Y_seg, V, Z, Q, F, U, K, W, LB, UB, num_logs, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, probvec_V, probvec_Z, probvec_Q, probvec_F, V_left, P0, minimum_n, open_segment, end_point, sample_state)
}

#' @title shift_function: This function takes in the current state of the MCMC and employ a position shift of a breakpoint.
#' all the input parameters described below refers to their most recent values.
#' @param S (int). The total number of interarrivals (intervals).
#' @param Tvec (const NumericVector). Vector of the observed time stamps in the update interval
#' @param Yvec (const IntegerVector). Vector of the observed messages in the update interval
#' @param U (const int&) Number of levels for the V state
#' @param K (const int&) Number of levels of the Z state
#' @param W (const int&) Number of levels for the Q state
#' @param probvec_V (const NumericVector&) Probability mass for the V state distribution
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_Q (const NumericVector&) Probability mass for the Q state distribution
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param lambdamat (const NumericMatrix&) probability weights ruling the message composition of the segments for the different levels of the V state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state.
#' @param num_logs (const int). Total numer of different logs (levels of the factor )
#' @param Bvec (NumericVector). Current vector of changepoints
#' @param Zvec (IntegerVector). Current vector with Z state of each  segment
#' @param Qvec (IntegerVector). Current vector with Q state of each  segment
#' @param Vvec (IntegerVector). Current vector with V state of each  segment
#' @param Fvec (IntegerVector). Current vector with F state of each  segment
#' @param Jss1 (const double). Probability to propose a forward move
#' @param Js1s (const double). Probability to propose a backward move
#' @param P0 (const double&) probability of observing a non-empty segment after a empty one
#' @param minimum_n (const int&) minimum number of observations in a non-empty segment
#' @param start_point (double, default is 0.0) start of the update interval
#' @param end_point (double, default is 0.0) end of the update interval; to be used for partially observed segments
#' @name shift_function
shift_function <- function(S, Tvec, Yvec, U, K, W, probvec_V, probvec_Z, probvec_Q, probvec_F, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, num_logs, Bvec, Zvec, Qvec, Vvec, Fvec, Jss1, Js1s, P0, minimum_n, start_point = 0.0, end_point = 0.0) {
    invisible(.Call(`_RJSMC_shift_function`, S, Tvec, Yvec, U, K, W, probvec_V, probvec_Z, probvec_Q, probvec_F, lambdamat, keyvec, etavec, key0vec, eta0vec, alphavec, muvec, num_logs, Bvec, Zvec, Qvec, Vvec, Fvec, Jss1, Js1s, P0, minimum_n, start_point, end_point))
}

#' @title Function for creating ax frequency table.
#' @param X NumericVector. Vector whose element are used to create the frequency table
#' @param K Integer. The number of classes -max(X) standard choice-
#' @param inc_zero Boolean. inc_zero==F (default) if the 0's must not be taken into account in the counting.
#' @return The frequency vector (NumericVector)
make_table <- function(X, K, inc_zero = FALSE) {
    .Call(`_RJSMC_make_table`, X, K, inc_zero)
}

#' @title Function to assign each element of a vector "x" to one of N  unique intervals defined through the
#' vector of breakpoint B; \code{B[j]<=x<B[j+1]} j=1...N+1. The out is "j"
#' @param x NumericVector. Vector  whose element need to ble allocated
#' @param breaks NumericVector. Vector containing the N+1 breakpoints
#' @return IntegerVector having the same size as x. Each element contains the index referring to the interval \code{x[i]} belongs to
#' @export
cpp_findInterval <- function(x, breaks) {
    .Call(`_RJSMC_cpp_findInterval`, x, breaks)
}

saveRObject <- function(rObject, filename) {
    invisible(.Call(`_RJSMC_saveRObject`, rObject, filename))
}

#' @title augment_vecZQFV
#' Function for augment/updating the state vectors (Zvec, Vvec, Fvec) as resulting from accepting a forward step
#' @param vec (IntegerVector&) vector to be augmented
#' @param left_value (const int) state value of the new left segment
#' @param right_value (const int) state value of the new right segment
#' @param IN (const int) index of the the  segment splitted(range is (1,S) )
#' @param S (const int) number of current segments
#' @return void no output is returned because the input (vec) is passed by reference and hence modified
#' @export
augment_vecZQFV <- function(vec, left_value, right_value, IN, S) {
    invisible(.Call(`_RJSMC_augment_vecZQFV`, vec, left_value, right_value, IN, S))
}

#' @title augment_vecM
#' Function for augment/updating the state vector Mvec as resulting from accepting a forward step
#' @param vec (NumericVector&) vector to be augmented
#' @param left_value (const double) state value of the new left segment
#' @param right_value (const double) state value of the new right segment
#' @param IN (const int) index of the  segment splitted (range is (1,S) )
#' @param S (const int) number of current segments
#' @return void no output is returned because the input (vec) is passed by reference and hence modified
#' @export
augment_vecM <- function(vec, left_value, right_value, IN, S) {
    invisible(.Call(`_RJSMC_augment_vecM`, vec, left_value, right_value, IN, S))
}

#' @title reduce_vecZQFV
#' Function for reducing/updating the state vectors (Zvec, Vvec, Fvec) as resulting from accepting a backward step
#' @param vec (IntegerVector&) vector to be augmented
#' @param  (const int) state value of the new segment
#' @param BR (const int) index of the removed breakpoint (range (1,S-1) )
#' @param S (const int) number of current segments
#' @return void no output is returned because the input (vec) is passed by reference and hence modified
#' @export
reduce_vecZQFV <- function(vec, value, BR, S) {
    invisible(.Call(`_RJSMC_reduce_vecZQFV`, vec, value, BR, S))
}

#' @title reduce_vecM
#' Function for reducing/updating the state vector Mvec as resulting from accepting a backward step
#' @param vec (NumericVector&) vector to be augmented
#' @param  (const double) state value of the new segment
#' @param BR (const int) index of the removed breakpoint (range (1,S-1) )
#' @param S (const int) number of current segments
#' @return void no output is returned because the input (vec) is passed by reference and hence modified
#' @export
reduce_vecM <- function(vec, value, BR, S) {
    invisible(.Call(`_RJSMC_reduce_vecM`, vec, value, BR, S))
}

#' @title augment_Bvec
#' Function for augmentig the breakpoint vector Bvec as result from accepting a forward step
#' @param vec (NumericVector&) vector with breakpoint
#' @param T_p (const double) vector to be inserted
#' @param IN (const int) index of the segment splitted
#' @param S (const int) number of current segments
#' @return void no output is returned because the input (vec) is passed by reference and hence modified
#' @export
augment_Bvec <- function(Bvec, T_p, IN, S) {
    invisible(.Call(`_RJSMC_augment_Bvec`, Bvec, T_p, IN, S))
}

#' @title reduce_Bvec
#' Function for reducing the breakpoint vector Bvec as result from accepting a backward step
#' @param vec (NumericVector&) vector with breakpoint
#' @param BR (const int) index of the breakpoint to be removed
#' @param S (const int) number of current segments
#' @return void no output is returned because the input (vec) is passed by reference and hence modified
#' @export
reduce_Bvec <- function(Bvec, BR, S) {
    invisible(.Call(`_RJSMC_reduce_Bvec`, Bvec, BR, S))
}

#' @title weights_correction
#' Function for computing the weights correction based on the importance density for a segment
#' @param T_seg Vector with time stamps within the update interval
#' @param break_sample_output (const List&) List of breakpoint vectors generated with the Importance Sampling
#' @param M (const int&) number of iteration performed in the Importance Sampling
#' @param K (const int&) Number of levels of the Z state
#' @param keyvec (const NumericVector&) Shape parameters ruling the length of non-empty segments in different levels of Z state
#' @param etavec (const NumericVector&) Mean parameters ruling the length of non-empty segments in different levels of Z state
#' @param key0vec (const NumericVector&) Shape parameters ruling the length of empty segments in different levels of F state
#' @param eta0vec (const NumericVector&) Mean parameters ruling the length of empty segments in different levels of F state
#' @param probvec_Z (const NumericVector&) probability mass for the Z state
#' @param probvec_F (const NumericVector&) probability mass for the F state
#' @param probvec_Q (const NumericVector&) probability mass for the Q state
#' @param alphavec (const NumericVector&) Shape parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param muvec (const NumericVector&) Mean parameters ruling the rate of occurrence of segment for the different levels of the Q state
#' @param minimum_n (const int&) minimum number of observations that must be observed in a non-empty segment
#' @param W (const int&) Number of levels for the Q state
#' @param P0 (const double&) Probability to observe an empty segment after a non-empty one
#' @return correction weight (double)
#' @export
weigths_correction <- function(T_seg, break_sample_output, M, K, keyvec, etavec, key0vec, eta0vec, probvec_Z, probvec_F, probvec_Q, alphavec, muvec, W, P0) {
    .Call(`_RJSMC_weigths_correction`, T_seg, break_sample_output, M, K, keyvec, etavec, key0vec, eta0vec, probvec_Z, probvec_F, probvec_Q, alphavec, muvec, W, P0)
}

